jobfinder/jobfinder_compte/urls.py
from django.urls import path, include
from .views import *

app_name = "jobfinder_compte"

urlpatterns = [
    # Connexion-Log in
    path('connexion_entreprise/', connexion_entreprise, name='connexion_entreprise'),
    path('connexion_user/', connexion_user, name='connexion_user'),
    path('entreprise_form/', entreprise_form, name='entreprise_form'),

    path('user_form/', user_form, name='user_form'),
    path('entreprise_page/', entreprise_page, name='entreprise_page'),
    path('user_page/', user_page, name='user_page'),
    path('update_user/<int:pk>', update_user_bis, name='update_user'),
    path('update_entreprise/<int:pk>', update_entreprise, name='update_entreprise'),
    path('update_annonce/<int:pk>', update_annonce, name='update_annonce'),
    path('delete_particulier/<int:pk>', delete_particulier, name='delete_particulier'),
    path('delete_entreprise/<int:pk>', delete_entreprise, name='delete_entreprise'),
    path('delete_annonce/<int:pk>', delete_annonce, name='delete_annonce')



]

jobfinder/jobfinder_compte/templates/connexion_entreprise.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Connexion Entreprise</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
    </head>
    <body>
        <header>
            <nav>
              <!-- logo -->
              <div class="logo">
                <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
              </div>
            </nav>
        </header>
        <main>
            <h1>Connexion Entreprise</h1>
            {%for message in messages%}
                <p>{{ message }} </p>
            {%endfor%}
            <form method="POST">
            {% csrf_token %}
                <div class="element">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="input" required/>
                </div>
                <div class="element">
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" class="input" required/>
                </div>
                <div class="submit_div">
                    <label for="submit"></label>
                    <input type="submit" name="submit" class="submit">
                </div>
            </form>

        </main>
    </body>
</html>

jobfinder/jobfinder_compte/templates/connexion_user.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Connexion Particulier</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
    </head>
    <body>
        <header>
            <nav>
              <!-- logo -->
              <div class="logo">
                <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
              </div>
            </nav>
        </header>
        <main>
            <h1>Connexion Particulier</h1>
            <div class="message">
                {%for message in messages%}
                    <p>{{ message }} </p>
                {%endfor%}
            </div>
            <form method="POST">
            {% csrf_token %}
                <div class="element">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="input" required/>
                </div>
                <div class="element">
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" class="input" required/>
                </div>
                <div class="submit_div">
                    <input type="submit" name="submit" class="submit">
                </div>
            </form>
        </main>
    </body>
</html>

jobfinder/jobfinder_compte/templates/entreprise_form.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Formulaire entreprise</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
    </head>
    <body>
      <header>
        <nav>
          <!-- logo -->
          <div class="logo">
            <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
          </div>
        </nav>
    </header>
        <main>
          <form method="POST">
            {% csrf_token %}
            <h2><center>Création de votre compte entreprise</center></h2>
            <!-- nom entreprise -->
            <div class="element">
              <label for="nom_entreprise">Nom de votre entreprise</label>
              <input type="text" name="nom_entreprise" id="nom_entreprise" class="input" required>
            </div>
            <!-- pageweb -->
            <div class="element">
              <label for="pageweb">Votre page web</label>
              <input type="url" name="pageweb" id="pageweb" class="input" required>
            </div>
            <!-- adresse -->
            <div class="element">
              <label for="adresse">Votre adresse</label>
              <input type="text" name="adresse" id="adresse" class="input" required>
            </div>
            <!-- taille entreprise -->
            <div class="element">
              <label for="taille">Taille de votre entreprise</label>
              <select name="taille" id="taille" class="input">
                <option value="0-10"> 0-10 employés </option>
                <option value="10-250"> 10-250 employés </option>
                <option value="250-5000"> 250-5000 employés </option>
                <option value="+5000"> +5000 employés </option>
              </select>
            </div class="element">
            <!-- description de l'entreprise -->
            <div class="element">
              <label for="description">Description de votre entreprise</label>
              <textarea name="description" id="description" placeholder="Votre description" required></textarea>
            </div>
            <!-- email -->
            <div class="element">
              <label for="email">Votre email</label>
              <input type="email" name="email" id="email" class="input" required>
            </div>
            <!-- mot de passe -->
            <div class="element">
              <label for="password">Choisissez un mot de passe</label>
              <input type="password" name="password" id="password"class="input" required>
            </div class="element">
            <!-- confirmation de mot de passe -->
            <div class="element">
              <label for="cmdp">Confirmez votre mot de passe</label>
              <input type="password" name="cmdp" id="cmdp" class="input" required >
            </div>
            <!-- boutton envoyer -->
            <div class="submit_div">
              <br>
              <input type="submit" class="button-1 submit" value="Inscription">
            </div>
          </form>
          {%for message in messages%}
            <p>{{ message }} </p>
          {%endfor%}
        </main>
        <footer>
          
          <h3><center>Contactez-nous pour trouver votre job de rêve</center></h3>
          <div class="info-G">
            <h4 class="infos">A propos de jobfinder</h4>
            <p class="infos">Email : findyourdreamjob@jobfinder.com </p>
            <p class="infos">Telephone : 01-45-02-65-16</p>
            <p class="infos">Siège social : 36 Quai des Orfèvres, <br>75016 Paris </p>
            <p class="infos">SIRET :  91326852000065 </p>
          </div>
         <div class="reseaux-J">
          <div class="reseaux">
            <h4>Nos réseaux sociaux : </h4>
            <ul>
              <a class="loo" href="https://www.instagram.com/hoppy.epitech/" ><img class="logo-footer" src="{% static 'img/Logo_Insta.png' %}" alt=""></a>
              <a class="loo" href="https://www.linkedin.com/school/epitech---european-institute-of-technology/posts/?feedView=all" ><img class="logo-footer" src="{% static 'img/Logo_LinkedIn.png' %}" alt=""></a>
              <a class="loo" href="https://x.com/Epitech" ><img class="logo-footer" src="{% static 'img/Logo_X.png' %}" alt=""></a>
              <a class="loo" href="" ><img src="{% static 'img/Logo_dispo.png' %}" class="logo-footer" alt=""></a>
              <!-- <a  href="" ><img class="logo-footer" src="" alt="">App store</a> -->
            </ul>
          </div>
          <div class="info-J">
            <p class="mention"><center>CGV</center></p>
            <p class="mention"><center> - </center></p>
            <p class="mention"><center>Mentions légales</center></p>
            <p class="mention"><center> - </center></p>
            <p class="mention"><center>Traitement de données</center></p>
          </div>
        </div>
        </footer>
    </body>
</html>

jobfinder/jobfinder_compte/templates/entreprise_page.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>Profil entreprise</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'new_css/style_pages.css' %}">
  </head>
    <body>
      <header>
        <nav>
          <!-- logo -->
          <div class="logo">
            <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
          </div>

          <div class="log">
            <a href="{% url 'jobfinder_compte:user_page'%}" class="button-1 connexion">
            {% for entreprise in entreprises %}
              {% if user.id == entreprise.user_id%}
                {{entreprise.nom_entreprise}}
                {% endif %}
            {% endfor %}</a>
            <a href="{% url 'logout_user' %}" method="post" class="button-1 inscription">Se déconnecter</a>
          </div>
        </nav>
    </header>
        <main>

          <!-- Popup création d'annonce -->

          {% if messages %}
            <div id="message-popup" style="display:none;">
              {% for message in messages %}
                  <p class="message {{ message.tags }}">{{ message }}</p>
              {% endfor %}
            </div>
          {% endif %}


          <div class="myInfo">
          {% for entreprise in entreprises %}
        {% if user.id == entreprise.user_id%}
          <h1> {{entreprise.nom_entreprise}} </h1>
          <h2> {{entreprise.pageweb}} </h2>
          <p class="info"><u>Adresse:</u><br>{{entreprise.adresse}} </p>
          <p class="info"><u>Taille:</u> <br>{{entreprise.taille}} </p>
          <p class="info"><u>Description:</u> <br>{{entreprise.description}} </p>
        {% endif %}
        {% endfor %}
        </div>

        <div class="log">
          <a href="/jobfinder/annonce_form/{{user.pk}}" class="button-1 inscription"> Créer une nouvelle annonce </a>
          <a href="/compte/update_entreprise/{{user.pk}}" class="button-1 connexion"> Mettre à jour mes informations </a>
          <a href="/compte/delete_entreprise/{{user.pk}}" class="button-1 suppr"> Supprimer mon compte </a>
        </div>

        <!-- Section Annonces  -->
        <div class="allEncart">

          {% for annonce in annonces %}

            {% if annonce.entreprise_id == user.id %}

              <div class="jobEncart">

                <div class="jobTitle">
                  <h3 class="annonceTitre">{{annonce.titre}}</h3>
                  <h6 class="annonceElement"><u>Adresse:</u> <br>{{annonce.adresse}}</h6>
                  <h6 class="annonceElement"><u>Entreprise:</u><br>{{annonce.nom_entreprise}}</h6>
                  <h6 class="annonceElement"><u>Type de contrat:</u><br>{{annonce.contrat}}</h6>
                  <h6 class="annonceElement"><u>Date de publication:</u><br>{{annonce.date}}</h6>
                  <h6 class="annonceElement"><u>Fourchette de salaire:</u><br>{{annonce.salaire}}</h6>
                </div>

                <div class="short_description">
                  <p>Description courte:<br>{{annonce.short_description}}</p>
                </div>

                <div class="long_description">
                  <p>Description longue:<br>{{annonce.long_description}}</p>
                </div>

                <!-- Candidature de chaque annonce -->
                <div class="candidatures" style="display: none;">

                  <h3><center>Voici les candidatures reçues pour cette offre</center></h3>
                  {% for candidature in candidatures %}

                    {% if candidature.annonce_id == annonce.id %}
                
                      <div class="encartCand">
                        <h5 class="candElement">Prénom : {{candidature.prenom}}</h5>
                        <h5 class="candElement">Nom : {{candidature.nom}}</h5>
                        <h5 class="candElement">Email : {{candidature.email}}</h5>
                        <h5 class="candElement">Telephone : {{candidature.telephone}}</h5>
                      </div>

                    {% endif %}

                  {% endfor %}

                </div>

                <div class="buttons">
                  <a href="/compte/update_annonce/{{annonce.pk}}"><button class="button-1 modif">Modifier l'annonce</button></a>
                  <button class="button-1 learnMore">Voir les Candidatures</button>
                  <a href="/compte/delete_annonce/{{annonce.pk}}"><button class="button-1 suppr">Supprimer l'annonce</button></a>
                </div>

              </div>

            {% endif %}

          {% endfor %}

        </div>

        </main>
        <footer>
          
          <h3><center>Contactez-nous pour trouver votre job de rêve</center></h3>
          <div class="info-G">
            <h4 class="infos">A propos de jobfinder</h4>
            <p class="infos">Email : findyourdreamjob@jobfinder.com </p>
            <p class="infos">Telephone : 01-45-02-65-16</p>
            <p class="infos">Siège social : 36 Quai des Orfèvres, <br>75016 Paris </p>
            <p class="infos">SIRET :  91326852000065 </p>
          </div>
         <div class="reseaux-J">
          <div class="reseaux">
            <h4>Nos réseaux sociaux : </h4>
            <ul>
              <a class="loo" href="https://www.instagram.com/hoppy.epitech/" ><img class="logo-footer" src="{% static 'img/Logo_Insta.png' %}" alt=""></a>
              <a class="loo" href="https://www.linkedin.com/school/epitech---european-institute-of-technology/posts/?feedView=all" ><img class="logo-footer" src="{% static 'img/Logo_LinkedIn.png' %}" alt=""></a>
              <a class="loo" href="https://x.com/Epitech" ><img class="logo-footer" src="{% static 'img/Logo_X.png' %}" alt=""></a>
              <a class="loo" href="" ><img src="{% static 'img/Logo_dispo.png' %}" class="logo-footer" alt=""></a>
              <!-- <a  href="" ><img class="logo-footer" src="" alt="">App store</a> -->
            </ul>
          </div>
          <div class="info-J">
            <p class="mention"><center>CGV</center></p>
            <p class="mention"><center> - </center></p>
            <p class="mention"><center>Mentions légales</center></p>
            <p class="mention"><center> - </center></p>
            <p class="mention"><center>Traitement de données</center></p>
          </div>
        </div>
        </footer>
        <script>

          const learnMoreButton = document.querySelectorAll(".learnMore")

            learnMoreButton.forEach(button => {
              button.addEventListener("click", function(){

              const jobEncart = button.closest(".jobEncart")

              const longDescription = jobEncart.querySelector(".candidatures")

              if (longDescription.style.display == "none"){
                longDescription.style.display = "block"
                button.textContent = "Cacher les Candidatures"
              }else{
                longDescription.style.display = "none"
                button.textContent = "Voir les Candidatures"
              }
            });
          })

          const messagePopup = document.getElementById('message-popup');
        
          if (messagePopup && messagePopup.innerText.trim() !== "") {
              // Créer le popup
              alert(messagePopup.innerText); 
        }

        </script>
    </body>
</html>

jobfinder/jobfinder_compte/templates/remove-annonce.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>Supprimer annonce</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
</head>
<body>
    <header>
        <nav>
          <!-- logo -->
          <div class="logo">
            <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
          </div>

        </nav>
    </header>
    <main>
      <center>
      <div class="remove">
        <form action="" method="POST">
          {% csrf_token %}
        
          <div class="alert alert-danger" role="alert">
              <center>Etes-vous sûr de vouloir supprimer "{{annonce.titre}}"?</center>
          </div>

          <p class="submitDiv">
              <a href="{% url 'jobfinder_compte:entreprise_page' %}" class="submit" >--Return</a>
              <input type="submit" class="submit" value="Confirm">
          </p>
        </form>
      </div>
      </center>
    </main>
    </body>
</html>

jobfinder/jobfinder_compte/templates/remove-entreprise.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>Supprimer compte entreprise</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
</head>
<body>
    <header>
        <nav>
          <!-- logo -->
          <div class="logo">
            <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
          </div>

        </nav>
    </header>
    <main>
      <div class="remove">
        <form action="" method="POST">
          {% csrf_token %}
        
          <div class="alert alert-danger" role="alert">
              <center>Etes-vous sûr de vouloir supprimer "{{entreprise.nom_entreprise}}"?</center>
          </div>

          <p class="submitDiv">
              <a href="{% url 'jobfinder_compte:entreprise_page' %}" class="submit" >--Return</a>
              <input type="submit" class="submit" value="Confirm">
          </p>
        </form>
      </div>
    </main>
    </body>
</html>

jobfinder/jobfinder_compte/templates/remove-particulier.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>Profil particuliers</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
</head>
<body>
    <header>
        <nav>
          <!-- logo -->
          <div class="logo">
            <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
          </div>

        </nav>
    </header>
    <main>
      <div class="remove">
        <form action="" method="POST">
          {% csrf_token %}
        
          <div class="alert alert-danger" role="alert">
              <center>Etes-vous sûr de vouloir supprimer "{{particulier.nom}}"?</center>
          </div>

          <p class="submitDiv">
              <a href="{% url 'jobfinder_compte:user_page' %}" class="submit" >--Return</a>
              <input type="submit" class="submit" value="Confirm">
          </p>
        </form>
      </div>
    </main>
    </body>
</html>

jobfinder/jobfinder_compte/templates/update_entreprise.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Mise à jour profil Entreprises</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'new_css/style_pyForm.css' %}">
    </head>
    <body>
        <header>
            <nav>
              <!-- logo -->
              <div class="logo">
                <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
              </div>

            </nav>
        </header>
        <main>
          {% if user.is_authenticated %}
            {% if user.is_entreprise == True%}
            <form method="POST">
              {%for message in messages%}
                <p>{{ message }} </p>
              {%endfor%}
              {% csrf_token %}
              {{form1.as_p}}
              {{form2.as_p}}
              <input type="submit" class="submit">
            </form>
            {% endif %}
          {% endif %}

        </main>
    </body>
</html>

jobfinder/jobfinder_compte/templates/update_user.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Mise à jour profil particuliers</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'new_css/style_pyForm.css' %}">
    </head>
    <body>
        <header>
            <nav>
              <!-- logo -->
              <div class="logo">
                <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
              </div>

            </nav>
        </header>
        <main>
          {% if user.is_authenticated %}
          {% if user.is_particulier == True%}
            <form method="POST">
              {% csrf_token %}
              {{form1.as_p}}
              {{form2.as_p}}
              <input type="submit" class="submit">
            </form>
          {% endif %}
          {% endif %}
          
        </main>

    </body>
</html>

jobfinder/jobfinder_compte/templates/user_form.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Formulaire particuliers</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'new_css/style_form.css' %}">
    </head>
    <body>
        <header>
            <nav>
              <!-- logo -->
              <div class="logo">
                <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
              </div>
            </nav>
        </header>
        <main>
            <form method="POST">
                {% csrf_token %}
                <h2><center>Création de votre compte particulier</center></h2>
                {%for message in messages%}
                    <p><center>{{ message }}</center></p>
                {%endfor%}
                <div class="element">
                    <label for="nom">Nom</label>
                    <input type="text" name="nom" class="input" required>
                </div>
                <div class="element">
                    <label for="prenom">Prénom</label>
                    <input type="text" name="prenom" class="input" required>
                </div>
                <div class="element">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="input" required>
                </div>
                <div class="element">
                    <label for="telephone">Téléphone</label>
                    <input type="text" name="telephone" maxlength="10" class="input">
                </div>
                <div class="element">
                    <label for="cmdp">Mot de passe</label>
                    <input type="password" name="cmdp" class="input" required>
                </div>
                <div class="element">
                    <label for="password">Confirmation du mot de passe</label>
                    <input type="password" name="password" class="input" required>
                </div>
                <div class="submit_div">
                    <input type="submit" name="submit" class="button-1 submit" value="Inscription">
                </div>
            </form>

        </main>
        <footer>
          
            <h3><center>Contactez-nous pour trouver votre job de rêve</center></h3>
            <div class="info-G">
              <h4 class="infos">A propos de jobfinder</h4>
              <p class="infos">Email : findyourdreamjob@jobfinder.com </p>
              <p class="infos">Telephone : 01-45-02-65-16</p>
              <p class="infos">Siège social : 36 Quai des Orfèvres, <br>75016 Paris </p>
              <p class="infos">SIRET :  91326852000065 </p>
            </div>
           <div class="reseaux-J">
            <div class="reseaux">
              <h4>Nos réseaux sociaux : </h4>
              <ul>
                <a class="loo" href="https://www.instagram.com/hoppy.epitech/" ><img class="logo-footer" src="{% static 'img/Logo_Insta.png' %}" alt=""></a>
                <a class="loo" href="https://www.linkedin.com/school/epitech---european-institute-of-technology/posts/?feedView=all" ><img class="logo-footer" src="{% static 'img/Logo_LinkedIn.png' %}" alt=""></a>
                <a class="loo" href="https://x.com/Epitech" ><img class="logo-footer" src="{% static 'img/Logo_X.png' %}" alt=""></a>
                <a class="loo" href="" ><img src="{% static 'img/Logo_dispo.png' %}" class="logo-footer" alt=""></a>
                <!-- <a  href="" ><img class="logo-footer" src="" alt="">App store</a> -->
              </ul>
            </div>
            <div class="info-J">
              <p class="mention"><center>CGV</center></p>
              <p class="mention"><center> - </center></p>
              <p class="mention"><center>Mentions légales</center></p>
              <p class="mention"><center> - </center></p>
              <p class="mention"><center>Traitement de données</center></p>
            </div>
          </div>
          </footer>
    </body>
</html>

jobfinder/jobfinder_compte/templates/user_page.html
{%load static%}
<!DOCTYPE html>
<html>

<head>

  {%if a == true%}
  <script type="text/javascript">
      alert('Felicitation vous voila connecte');
  </script>
  {%endif%}
  {% csrf_token %}
  <title>Profil particuliers</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'new_css/style_pages.css' %}">
</head>

<body>
  
  <header>
    <nav>
      <!-- logo -->
      <div class="logo">
        <a href="{% url 'home_page'%}"><img src="{% static 'img/Logo_main.png' %}" class="logo_img"></a>
      </div>

      <!-- Vérifié si l'utilisateur est connecté -->
      <!-- {% if user.is_authenticated %}

          {% if user.is_particulier == True%} -->

      <div class="log">
        <a href="{% url 'jobfinder_compte:user_page'%}" class="button-1 connexion">
          {% for particulier in particuliers %}
          {% if user.id == particulier.user_id%}
          {{particulier.prenom}}
          {% endif %}
          {% endfor %}</a>
        <a href="{% url 'logout_user' %}" method="post" class="button-1 inscription">Se déconnecter</a>
      </div>

      <!-- {% else %}

          <div class="log">
            <a href="{% url 'jobfinder_compte:entreprise_page'%}" class="button-1 inscription"> Mon compte pro </a>
          </div>
          {% endif %}

        {% endif %} -->

    </nav>
  </header>
  <main>
    <div class="myInfo">
      <!-- Montrer les informations utilisateurs -->
      {% for particulier in particuliers %}
      {% if user.id == particulier.user_id%}
      <h2>Bienvenue <br>{{particulier.prenom}} {{particulier.nom}}</h2>
      <p class="info">Telephone :<br> {{particulier.telephone}} </p>
      <p class="info">Email :<br> {{user.email}} </p>
      {% endif %}
      {% endfor %}
    </div>
    <div class="log">
      <a href="/compte/update_user/{{user.pk}}" class="button-1 connexion"> Mettre à jour mes informations </a>
      <a href="/compte/delete_particulier/{{user.pk}}" class="button-1 suppr"> Supprimer mon compte </a>
    </div>
    <!-- Ici affichage des candidatures -->

    <h3>
      <center>Vos Candidatures :</center>
    </h3>
    {% for candidature in candidatures %}

    {% if candidature.user_id == user.id %}

    {% for annonce in annonces %}

    {% if candidature.annonce_id == annonce.id %}

    <div class="jobEncart">
      <h3 class="jobTitle"><u>Titre : </u> {{ annonce.titre }} </h3>
      <h5 class="annonceElement"><u>Nom de l'entreprise : </u><br>{{annonce.nom_entreprise}}</h5>
      <h5 class="annonceElement"><u>Adresse : </u><br> {{annonce.adresse}}</h5>
    </div>

    {% endif %}

    {% endfor %}

    {% endif %}

    {% endfor %}

  </main>
  <footer>

    <h3>
      <center>Contactez-nous pour trouver votre job de rêve</center>
    </h3>
    <div class="info-G">
      <h4 class="infos">A propos de jobfinder</h4>
      <p class="infos">Email : findyourdreamjob@jobfinder.com </p>
      <p class="infos">Telephone : 01-45-02-65-16</p>
      <p class="infos">Siège social : 36 Quai des Orfèvres, <br>75016 Paris </p>
      <p class="infos">SIRET : 91326852000065 </p>
    </div>
    <div class="reseaux-J">
      <div class="reseaux">
        <h4>Nos réseaux sociaux : </h4>
        <ul>
          <a class="loo" href="https://www.instagram.com/hoppy.epitech/"><img class="logo-footer"
              src="{% static 'img/Logo_Insta.png' %}" alt=""></a>
          <a class="loo"
            href="https://www.linkedin.com/school/epitech---european-institute-of-technology/posts/?feedView=all"><img
              class="logo-footer" src="{% static 'img/Logo_LinkedIn.png' %}" alt=""></a>
          <a class="loo" href="https://x.com/Epitech"><img class="logo-footer" src="{% static 'img/Logo_X.png' %}"
              alt=""></a>
          <a class="loo" href=""><img src="{% static 'img/Logo_dispo.png' %}" class="logo-footer" alt=""></a>
          <!-- <a  href="" ><img class="logo-footer" src="" alt="">App store</a> -->
        </ul>
      </div>
      <div class="info-J">
        <p class="mention">
          <center>CGV</center>
        </p>
        <p class="mention">
          <center> - </center>
        </p>
        <p class="mention">
          <center>Mentions légales</center>
        </p>
        <p class="mention">
          <center> - </center>
        </p>
        <p class="mention">
          <center>Traitement de données</center>
        </p>
      </div>
    </div>
  </footer>
</body>

</html>